name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    env:
      CI: true
      ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install additional dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev

    - name: Install additional dependencies for macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install gnu-tar

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm install
      timeout-minutes: 10

    - name: Build application
      run: |
        echo "Starting the build process..."
        npm run build
      timeout-minutes: 20

    - name: Run tests
      run: |
        echo "Running tests..."
        npm test
      timeout-minutes: 10

    - name: Check for GitHub Token
      id: check_token
      run: |
        if [ -z "$GH_TOKEN" ]; then
          echo "GH_TOKEN is not set."
          echo "GH_TOKEN_PRESENT=false" >> $GITHUB_ENV
        else
          echo "GH_TOKEN_PRESENT=true" >> $GITHUB_ENV
        fi

    - name: Package and Publish (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        if [ "$GH_TOKEN_PRESENT" = "true" ]; then
          echo "Publishing macOS artifacts..."
          npm run release
        else
          echo "Skipping publishing for macOS. GH_TOKEN is not set."
          npm run electron-build -- --publish=never
        fi
      timeout-minutes: 15
      continue-on-error: true

    - name: Package and Publish (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        if [ "$GH_TOKEN_PRESENT" = "true" ]; then
          echo "Publishing Windows artifacts..."
          npm run release
        else
          echo "Skipping publishing for Windows. GH_TOKEN is not set."
          npm run electron-build -- --publish=never
        fi
      timeout-minutes: 15
      continue-on-error: true

    - name: Package and Publish (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        if [ "$GH_TOKEN_PRESENT" = "true" ]; then
          echo "Publishing Linux artifacts..."
          npm run release
        else
          echo "Skipping publishing for Linux. GH_TOKEN is not set."
          npm run electron-build -- --publish=never
        fi
      timeout-minutes: 15
      continue-on-error: true

    - name: Archive build artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/

    - name: Cleanup caches
      if: failure() || cancelled()
      run: |
        echo "Cleaning up npm cache..."
        npm cache clean --force || echo "Failed to clean npm cache."

    - name: Final Status
      run: |
        echo "Build process completed."
        if [ "$GH_TOKEN_PRESENT" = "false" ]; then
          echo "Warning: GH_TOKEN was not set. Artifacts were not published."
        else
          echo "Artifacts were published successfully."
        fi
