name: Build, Test, and Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    env:
      CI: true
      ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        echo "Installing project dependencies..."
        npm install
        echo "Installing Electron dependencies..."
        npx electron-builder install-app-deps
      timeout-minutes: 15

    - name: Run ESLint with auto-fix
      run: |
        echo "Running ESLint with auto-fix..."
        npm run lint:fix || echo "ESLint found issues, but build will continue."
      timeout-minutes: 5
      continue-on-error: true  # Continue the build process even if linting fixes issues

    - name: Check for remaining linting errors
      run: |
        echo "Checking for remaining linting errors..."
        npm run lint
      timeout-minutes: 5
      continue-on-error: true  # Continue the build process even if linting has errors

    - name: Build application
      run: |
        echo "Building the application..."
        npm run build
      timeout-minutes: 30

    - name: Run tests
      run: |
        echo "Running tests..."
        npm test -- --ci --reporters=jest-junit --coverage
      timeout-minutes: 15

    - name: Check for GitHub Token
      id: check_token
      run: |
        if [ -z "$GH_TOKEN" ]; then
          echo "GH_TOKEN is not set. Skipping publishing steps."
          echo "GH_TOKEN_PRESENT=false" >> $GITHUB_ENV
        else
          echo "GH_TOKEN is set."
          echo "GH_TOKEN_PRESENT=true" >> $GITHUB_ENV
        fi
      timeout-minutes: 5

    - name: Package and Publish (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        echo "Handling macOS specific packaging..."
        if security find-identity -v -p codesigning; then
          echo "Code signing identity found, proceeding with signing and publishing."
          npm run release
        else
          echo "No code signing identity found, skipping code signing."
          npm run electron-build -- --publish=never
        fi
      timeout-minutes: 20
      continue-on-error: true

    - name: Package and Publish (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        echo "Handling Windows specific packaging..."
        if [ "$GH_TOKEN_PRESENT" = "true" ]; then
          echo "Publishing Windows artifacts..."
          npm run release
        else
          echo "GH_TOKEN is not set. Skipping publishing."
          npm run electron-build -- --publish=never
        fi
      timeout-minutes: 20
      continue-on-error: true

    - name: Package and Publish (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "Handling Linux specific packaging..."
        if [ "$GH_TOKEN_PRESENT" = "true" ]; then
          echo "Publishing Linux artifacts..."
          npm run release
        else
          echo "GH_TOKEN is not set. Skipping publishing."
          npm run electron-build -- --publish=never
        fi
      timeout-minutes: 20
      continue-on-error: true

    - name: Generate changelog and version bump
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        echo "Generating changelog and bumping version..."
        npm version patch -m "chore(release): %s"
        npx auto-changelog -p
        git push --follow-tags
      timeout-minutes: 10

    - name: Archive build artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/
      continue-on-error: false

    - name: Cleanup caches
      if: failure() || cancelled()
      run: |
        echo "Cleaning up npm cache..."
        npm cache clean --force || echo "Failed to clean npm cache."
      continue-on-error: true

    - name: Final Status
      run: |
        echo "Finalizing build process."
        if [ "$GH_TOKEN_PRESENT" = "false" ]; then
          echo "Warning: GH_TOKEN was not set. Artifacts were not published."
        else
          echo "Build completed successfully, and artifacts were published."
        fi
      continue-on-error: false
