name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: [18.x]

    env:
      CI: true  # Ensures the build is aware it’s running in a CI environment
      ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true
      GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Reference the GitHub Personal Access Token from secrets

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install additional dependencies for Linux
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev

    - name: Install additional dependencies for macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install gnu-tar

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Package and Publish (macOS Only)
      if: matrix.os == 'macos-latest'
      run: |
        if [ -z "$GH_TOKEN" ]; then
          echo "GH_TOKEN is not set. Skipping publication."
        else
          npm run release
        fi

    - name: Archive build artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: build/

    - name: Cleanup caches
      if: failure()
      run: |
        npm cache clean --force

    - name: Set up environment variables
      run: |
        echo "ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES=true" >> $GITHUB_ENV
        echo "CI=true" >> $GITHUB_ENV

