name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: 18.x
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Run tests
      run: npm run test:ci

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: coverage

  build:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: Build React app
      run: npm run react-build

    - name: Create placeholder icon if missing
      run: |
        if [ ! -f "public/icon.png" ]; then
          echo "Creating placeholder icon..."
          convert -size 512x512 xc:transparent -fill black -draw "circle 256,256 256,0" public/icon.png
        fi
        cp public/icon.png build/icon.png

    - name: Build Electron app
      run: npm run electron-build
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: List dist directory contents
      run: ls -R dist

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: Deploy
      run: |
        echo "Deployment step goes here"
        # Add your deployment logic here

  release:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Bump version and push tag
      id: tag_version
      uses: anothrNick/github-tag-action@1.71.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        DEFAULT_BUMP: patch
        WITH_V: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_tag }}
        body: |
          Changes in this Release
          - First Change
          - Second Change
        draft: false
        prerelease: false

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: dist
        path: dist

    - name: List dist directory contents
      run: ls -R dist

    - name: Find AppImage
      id: find_appimage
      run: |
        APPIMAGE=$(find dist -name "*.AppImage" | head -n 1)
        if [ -z "$APPIMAGE" ]; then
          echo "AppImage not found"
          echo "appimage_path=./README.md" >> $GITHUB_OUTPUT
          echo "appimage_name=AppImage-not-found.txt" >> $GITHUB_OUTPUT
        else
          echo "appimage_path=$APPIMAGE" >> $GITHUB_OUTPUT
          echo "appimage_name=$(basename $APPIMAGE)" >> $GITHUB_OUTPUT
        fi

    - name: Debug AppImage variables
      run: |
        echo "AppImage Path: ${{ steps.find_appimage.outputs.appimage_path }}"
        echo "AppImage Name: ${{ steps.find_appimage.outputs.appimage_name }}"

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.find_appimage.outputs.appimage_path }}
        asset_name: ${{ steps.find_appimage.outputs.appimage_name || 'fallback-asset-name.txt' }}
        asset_content_type: application/octet-stream

  cleanup:
    needs: [lint-and-test, build, deploy, release]
    if: always()
    runs-on: ubuntu-latest
    steps:
    - name: Delete old workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
        repository: ${{ github.repository }}
        retain_days: 30
        keep_minimum_runs: 6
